In [80]:
import pandas as pd
df= pd.read_csv('capstone/Street_Pothole_Work_Orders_-_Closed__Dataset_.csv')
null_counts = df[df.isna().any(axis=1)]
null_counts # almost every row has some sort of null

,the_geom,DefNum,InitBy,HouseNum,OFT,OnFaceName,OnPrimName,FrmPrimNam,ToPrimName,SpecLoc,Boro,Source,RptDate,RptClosed,Shape_Leng
0,MULTILINESTRING ((-73.88643460204372 40.630776...,DB2004041154,YRD,NaN,373480377030377030,ROCKAWAY PY,ROCKAWAY PARKWAY,BELT PARKWAY,BELT PARKWAY,NaN,B,YRD,02/08/2004,01/27/2023,557.690465
1,MULTILINESTRING ((-73.94380842208851 40.584992...,DB2004287021,CSC,NaN,318630377030377030,BEDFORD AV,BEDFORD AVENUE,BELT PARKWAY,BELT PARKWAY,SB ON BEDFORD_UNDERNEATH OVERPASS,B,CTZ,10/13/2004,02/14/2013,109.124234
2,MULTILINESTRING ((-73.98570910180842 40.641185...,DB2006085009,CSC,NaN,306380308480308530,13 AV,13 AVENUE,38 STREET,39 STREET,I/F/O B16 BUS STOP,B,CTZ,03/26/2006,10/11/2014,260.495098
6,MULTILINESTRING ((-73.92232548215823 40.586294...,DB2009362066,CSC,NaN,342890356960375990,GAIN CT,GAIN COURT,LOIS AVENUE,SEBA AVENUE,CLOSER TO SEBA AVE,B,CTZ,12/28/2009,01/05/2010,529.261511
9,MULTILINESTRING ((-73.95291388704382 40.706700...,DB2009364034,CSC,NaN,323230349430364630,BDWY,BROADWAY,HEWES STREET,NEW MONTROSE AVENUE,SEVERAL ON STREET,B,CTZ,12/30/2009,01/10/2010,304.584886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360725,MULTILINESTRING ((-73.9103319358796 40.8790380...,DX2024029015,ONF,NaN,268320223800274930,TIBBETT AV,TIBBETT AVENUE,DEAD END,WEST 230 STREET,THERE S MULTIPLE POTHOLES ALL THE WAY TO DEAD END,X,CTZ,01/29/2024,01/30/2024,250.556290
360726,MULTILINESTRING ((-73.89636314620641 40.858375...,DX2024030013,YRD,355,227180249420273720,E 184 ST,EAST 184 STREET,MARION AVENUE,WEBSTER AVENUE,NaN,X,YRD,01/26/2024,01/26/2024,844.117867
360727,MULTILINESTRING ((-73.85609688028005 40.856941...,DX2024030020,YRD,1150,257720278050278850,PELHAM PY S,PELHAM PARKWAY,WILLIAMSBRIDGE ROAD,YATES AVENUE,NaN,X,YRD,01/30/2024,01/30/2024,386.464657
360728,MULTILINESTRING ((-73.85273748942878 40.857237...,DX2024030021,YRD,1206,257720253350267840,PELHAM PY S,PELHAM PARKWAY,NARRAGANSETT AVENUE,TENBROECK AVENUE,NaN,X,YRD,01/30/2024,01/30/2024,308.600931
360729,MULTILINESTRING ((-73.85273748942878 40.857237...,DX2024030022,YRD,1220,257720253350267840,PELHAM PY S,PELHAM PARKWAY,NARRAGANSETT AVENUE,TENBROECK AVENUE,NaN,X,YRD,01/30/2024,01/30/2024,308.600931

In [59]:
null_count_in_the_geom =  df['the_geom'].isna().sum()  # 0 nulls

null_count_in_DefNum =  df['DefNum'].isna().sum() # 0 nulls

null_count_in_InitBy =  df['InitBy'].isna().sum() # 0 nulls

null_count_in_HouseNum =  df['HouseNum'].isna().sum() # 124730 nulls

null_count_in_OFT =  df['OFT'].isna().sum() # 0 nulls

null_count_in_OnFaceName =  df['OnFaceName'].isna().sum() # 663 nulls

null_count_in_OnPrimName =  df['OnPrimName'].isna().sum() # 77 nulls

null_count_in_FrmPrimNam =  df['FrmPrimNam'].isna().sum() # 30 nulls

null_count_in_ToPrimName =  df['ToPrimName'].isna().sum() # 106 nulls

null_count_in_SpecLoc =  df['SpecLoc'].isna().sum() # 240426 nulls

null_count_in_Boro =  df['Boro'].isna().sum() # 0 nulls

null_count_in_Source =  df['Source'].isna().sum() # 0 nulls

null_count_in_RptDate =  df['RptDate'].isna().sum() # 0 nulls

null_count_in_RptClosed =  df['RptClosed'].isna().sum() # 0 nulls

null_count_in_Shape_Leng =  df['Shape_Leng'].isna().sum() # 0 nulls

null_count_in_Shape_Leng

0

We have few nulls in the data but mostly in House_num and specific location and it is not going to help much with predicting. As we already have the other columns "OFT	OnFaceName	OnPrimName	FrmPrimNam	ToPrimName	" so I am going to drop columns "House_num" and 'SpecLoc'.

In [84]:
df = df.drop(['HouseNum', 'SpecLoc'], axis=1)

KeyError: "['HouseNum', 'SpecLoc'] not found in axis"

The data is not sorted so I will be sorting this data based on the pothole date reported and re-indexing.

In [85]:
df.sort_values('RptDate', inplace=True)
df

,the_geom,DefNum,InitBy,OFT,OnFaceName,OnPrimName,FrmPrimNam,ToPrimName,Boro,Source,RptDate,RptClosed,Shape_Leng
264288,MULTILINESTRING ((-74.13189065092838 40.606678...,DS2010002009,YRD,519700534886555100,BRADLEY AV,BRADLEY AVENUE,JULIE COURT,WESTWOOD AVENUE,S,YRD,01/01/2010,01/02/2010,396.447339
97388,MULTILINESTRING ((-73.94832657203315 40.808972...,DM2010002011,YRD,136270110610110810,W 125 ST,WEST 125 STREET,7 AVENUE,8 AVENUE,M,YRD,01/01/2010,01/02/2010,899.419609
97389,MULTILINESTRING ((-73.94982390395477 40.784515...,DM2010002013,YRD,118870110110110210,E 95 ST,EAST 95 STREET,2 AVENUE,3 AVENUE,M,YRD,01/01/2010,01/02/2010,711.456829
311758,MULTILINESTRING ((-73.84127784686363 40.880317...,DX2010001003,CSC,231220213820223800,ELY AV,ELY AVENUE,BOSTON ROAD,DEAD END,X,CTZ,01/01/2010,01/04/2010,647.522807
97386,MULTILINESTRING ((-73.95295166422682 40.808396...,DM2010002004,YRD,131190136210136230,ST NICHOLAS AV,ST NICHOLAS AVENUE,WEST 122 STREET,WEST 123 STREET,M,YRD,01/01/2010,01/02/2010,306.766137
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146011,MULTILINESTRING ((-73.98207933993069 40.772990...,DM2023365005,SPH,115710135070135090,COLUMBUS AV,COLUMBUS AVENUE,WEST 65 STREET,WEST 66 STREET,M,CTZ,12/31/2023,01/02/2024,263.263554
263866,MULTILINESTRING ((-73.71605950175363 40.727371...,DQ2023365010,SPH,427225418040439024,249 ST,249 STREET,89 AVENUE,CITY LIMIT,Q,CTZ,12/31/2023,01/09/2024,306.468100
97115,MULTILINESTRING ((-73.99937595780048 40.597810...,DB2023365003,ONF,330630316730317330,CROPSEY AV,CROPSEY AVENUE,BAY 29 STREET,BAY PARKWAY,B,CTZ,12/31/2023,01/02/2024,281.105102
146010,MULTILINESTRING ((-73.94069032811753 40.847387...,DM2023365002,CSC,130690128890137270,S PINEHURST AV,SOUTH PINEHURST AVENUE,PINEHURST AVENUE,WEST 176 STREET,M,CTZ,12/31/2023,01/02/2024,240.473929
263862,MULTILINESTRING ((-73.7625199304262 40.7411712...,DQ2023365001,SPH,414490426440426490,69 AV,69 AVENUE,212 STREET,213 STREET,Q,CTZ,12/31/2023,01/03/2024,260.813640